# Generated by Django 3.2.4 on 2021-07-10 17:05

import cofe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofe', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('media_url', models.ImageField(upload_to=cofe.models.About.get_file_name)),
            ],
        ),
    ]
